name: scheduled-pipeline

on:
  schedule: 
    # by default the time will be in UTC, don't forget to convert it into
    # IST. Add +5:30 in time to 
    - cron: '*/10 * * * *'   # after every 5 min
    # - cron: '17 5 * * *'
  push:
    branches:
      - main

jobs:
  pull-latest-model:   
    name: test schedule cicd feature         
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip

      - name: Update README with execution time
        run: python update.py
  
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with CI execution time"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Print Statement          # for debuging purpoer
        run: python ./main/testing.py
      